### ISSUE TITLE
Ontvangstdatum versus registratiedatum

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#103]
Op de detailpagina wordt nu getoond "ontvangstdatum".
Feitelijk wordt dit gevuld met de datum waarop een zaak is geregistreerd in het zaaksysteem.
Voor Woo-verzoeken is dat gelijk aan elkaar.
Voor convenanten (en straks ook andere informatiecategorieën) is de ontvangstdatum niet relevant of zelfs niet van toepassing.
Daarom is mijn vraag of dit veld bij de convenanten weggelaten kan worden?
En als dat niet kan om de term "ontvangstdatum" te vervangen door "registratiedatum".

**Comment by remko48** [comment]
Verwerkt en staat nu online op https://conductionnl.github.io/woo-website-epe/
