### ISSUE TITLE
De website moet op mobiel goed functioneren

### ISSUE THREAD

**Issue by remko48** [ConductionNL/woo-website-template#115]
Als gebruiker wil ik dat de Woo websites ook te gebruiken zijn op mobiel.

**Comment by remko48** [comment]
Pull request #130

**Comment by WillemIsendoorn** [comment]
Dit is bijna goed. Als ik het scherm smaller maak, dan wordt de knop "Zoeken" steeds kleiner. Op een gegeven moment valt die weg zonder dat die naar onder verplaatst wordt. De knop is dan helemaal weg.

**Comment by WillemIsendoorn** [comment]
Is akkoord zo.
