### ISSUE TITLE
Filteren op categorie werkt niet meer!

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#134]
Als ik op de hoofdpagina filter op Woo-verzoeken en besluiten  krijg ik geen zoekresultaten meer.
Als ik op Convenanten filter wél. Wat is hier aan de hand?

**Comment by remko48** [comment]
Ik zie het probleem een foutje met het doorgeven van de categorie aan de backend. Ik zal hier fix voor maken

**Comment by remko48** [comment]
[Pr](https://github.com/ConductionNL/woo-website-template/pull/135) van de fix

**Comment by remko48** [comment]
Fix staat online op de [Woo pagina van Epe](https://conductionnl.github.io/woo-website-epe/?Categorie=woo-verzoeken_en_-besluiten)

**Comment by WillemIsendoorn** [comment]
Dank voor de snelle reactie. Nu werkt het weer goed.
