### ISSUE TITLE
Probleem met dubbele labels voor documenten in backend

### ISSUE THREAD

**Issue by MWest2020** [ConductionNL/woo-website-template#139]
Er is  een probleem in de backend van ons systeem waarbij documenten meerdere labels kunnen hebben en er verwarring ontstaat bij het weergeven van deze documenten. Hier zijn de specifieke situaties:

- Als een document zowel het label "besluit" als "woo-publicatie" heeft, wordt het weergegeven in zowel "besluiten" als "bijlagen". Echter, we willen liever dat het document slechts in één categorie wordt weergegeven.

- Als een document zowel het label "en" als "woo-besluit" heeft, willen we dat het label "woo-bijlage" wordt genegeerd.

Mijn vraag is of dit probleem technisch kan worden opgelost, zodat er geen dubbele labels voorkomen en documenten correct in de juiste categorieën worden weergegeven.

**Comment by remko48** [comment]
Heeft @bbrands02 recent gedeployed
