### ISSUE TITLE
Dode link naar Wet Open Overheid op front page

### ISSUE THREAD

**Issue by janvlug** [ConductionNL/woo-website-template#280]
### Beschrijving van de bug

Het linkje naar meer informatie over de WOO op de main page werkt niet:
```
Meer informatie over de Wet Open Overheid kan [hier](https://www.open-overheid.nl/themas/wet-open-overheid/) worden gevonden.
```

Misschien is de informatie nu hier te vinden:
https://www.open-overheid.nl/onderwerpen/actieve-openbaarmaking

### Stappen om te reproduceren

Ga naar:
https://openwoo.app/

Click op [hier](https://www.open-overheid.nl/themas/wet-open-overheid/).

**Comment by remko48** [comment]
Bedankt voor het melden!

Er staat een aanpassing klaar in [deze pr](https://github.com/ConductionNL/woo-website-template/pull/282).

**Comment by remko48** [comment]
De pr is gemerged en staat online op [openwoo.app](https://openwoo.app/).
