### ISSUE TITLE
Card en Table

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#56]
Op de publicatiepagina staan nu de Engelse termen Cards en table.
Graag wijzigen naar Nederlandse termen.

**Comment by MWest2020** [comment]
Goed idee, zullen we dan "Tegels"voor Cards doen en "Tabel"voor Table?

**Comment by WillemIsendoorn** [comment]
Ik zou dan zeggen "Tegels" en "Tabel"

**Comment by MWest2020** [comment]
Top, gaan we regelen. @remko48 doet een snelle fix.
