### ISSUE TITLE
Balk met selectie van woo-categorie

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#57]
Het balkje waarin je via een pulldown menu een filter op de informatiecategorie kan zetten, is verdwenen.

**Comment by MWest2020** [comment]
Deze is inmiddels weer terug 

![image](https://github.com/ConductionNL/woo-website-template/assets/66728126/6b243ab3-97f0-43c5-b712-56c01ea1acf4)
