### ISSUE TITLE
Testcase 5 lijkt overbodig

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#59]
Deze testcase gaat over het verwijderen van een zaak. Voor een gebruiker is dit niet toegestaan dus deze test is eigenlijk niet nodig.

**Comment by rubenvdlinde** [comment]
Als in voor een gebruiker van het zaaksysteem? De gedachte achter de test is dat nu het archiveren/vernietigen van een zaak deze ook uit de WOO index moet verdwijnen.

**Comment by WillemIsendoorn** [comment]
Ja, een gebruiker van het zaaksysteem kan een zaak zelf niet verwijderen. Als de zaak per ongeluk is aangemaakt dan moet een functioneel beheerder dat doen. Het vernietigen is een bulkproces dat eenmaal per jaar wordt uitgevoerd. Dit is een behoorlijk formeel proces.
