### ISSUE TITLE
Inhoud lijst publicatietype

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#62]
De inhoud van het pulldownmenu onder Publicatietype komt nog niet overeen met de verkorte lijst met namen van de 11 informatiecategorieën.  Bijgaande document bevat in kolom B de juiste waarden voor deze lijst.

[Lijst verkorte namen informatiecategorieen.ods](https://github.com/ConductionNL/woo-website-template/files/12511650/Lijst.verkorte.namen.informatiecategorieen.ods)

**Comment by rubenvdlinde** [comment]
@remko48 dit klopt, @WillemIsendoorn heeft hier een punt. We zouden de door hem verwezen verkorte namen gebruiken op de index pagina.

**Comment by remko48** [comment]
Dan ga ik dat nu aanpassen 👍

**Comment by remko48** [comment]
Aangepast en overal geüpdatet
