### ISSUE TITLE
Weinig attributen te zien

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#82]
Afgelopen vrijdag heb ik een nieuwe zaak aangemaakt. Die werd nog niet zichtbaar op de Woo-pagina.
Nu wel!  Ik had echter veel meer gegevens verwacht in dit scherm. doen we iets niet goed?
![image](https://github.com/ConductionNL/woo-website-template/assets/143704052/7eeaea96-e832-4843-91ab-b803f672951a)

**Comment by MWest2020** [comment]
Hey Willem, 

Ook hier even de reactie. Sommige velden worden nog niet ondersteund, excuses voor de verwarring. Het beeld is dat dit snel opgelost wordt. Momenteel zijn de enige velden de getoonde velden nog. 

Ik hou je op de hoogte.
