### ISSUE TITLE
Taalfoutje

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#87]
Op de hoofdpagina staat:
![image](https://github.com/ConductionNL/woo-website-template/assets/143704052/9090b5ab-ba14-4166-854e-7f5728a8b0af)

Vind moet echter met dt geschreven worden.

**Comment by remko48** [comment]
Wordt meegenomen in de eerst volgende pr.

**Comment by remko48** [comment]
Verwerkt en gemerged
