### ISSUE TITLE
Datum besluit ontbreekt in detailscherm

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#88]
In het detailscherm ontbreekt de Datum besluit.
![image](https://github.com/ConductionNL/woo-website-template/assets/143704052/8b78c4b8-8558-4ce7-83c5-79a2e04e97f0)

Deze graag nog opnemen.
En qua volgorde zou ik zeggen: 
Ontvangstdatum
Datum besluit
Publicatiedatum

**Comment by remko48** [comment]
Alle kolommen op de detail pagina worden weergegeven als er informatie is om weer te geven.
In de binnenkomende data staan `Besluit` en `Besluitdatum` op `null` hierdoor geven wij de kolommen niet weer.

![image](https://github.com/ConductionNL/woo-website-template/assets/43807324/76ca205a-951f-444a-9807-89b446e8da43)

**Comment by WillemIsendoorn** [comment]
Hé dat is vreemd. Want in de zaak is de Datum besluit wél ingevuld.

**Comment by WillemIsendoorn** [comment]
Dit veld wordt wel degelijk meegestuurd in de externe zoekvraag. Het heet in het zaaksysteem ztc_datum_ besluit
Dit zou overeen moeten komen met woo_datum_besluit
Klopt de mapping wel? Of moeten wij nog iets doen.

**Comment by WillemIsendoorn** [comment]
Het veld woo_datum_besluit ontbrak nog. Dat is nu toegevoegd maar we zien het nog niet verschijnen.

**Comment by remko48** [comment]
Bij welk zaak/woo-object nummer hebben jullie dat toegevoegd? en staat deze zaak/woo-object wel al op https://conductionnl.github.io/woo-website-epe/ ?

**Comment by remko48** [comment]
Ik zie bij alle objecten namelijk nog geen besluit of besluit datum terug komen.
Een van de objecten die terug komt heeft zaak/woo-object nummer 131373

**Comment by WillemIsendoorn** [comment]
@remko48  Het gaat om zaak 131373 (Test 456)

**Comment by bbrands02** [comment]
@WillemIsendoorn Ik zie een ztc_datum_besluit terugkomen, die kan ik mappen. Volgens mij verwachtte we wel een woo_datum_besluit veld maar dat is nu geen groot probleem. Ik zal even toevoegen dat we eerst op woo_datum_besluit checken en anders ztc_datum_besluit.

**Comment by WillemIsendoorn** [comment]
@bbrands02 Volgens Petri levert ze woo_datum_besluit in zaak 131373 wél aan. Dat komt bij jullie niet binnen?

**Comment by remko48** [comment]
opgeloste en beschikbaar https://conductionnl.github.io/woo-website-epe/
