### ISSUE TITLE
Informatieverzoek wordt ook als bijlage getoond.

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#89]
Als ik maar één document aan de zaak koppel met alleen het label Informatieverzoek, dan wordt dat als Bijlage informatieverzoek getoond én als bijlage. Dat klopt volgens mij niet.

![image](https://github.com/ConductionNL/woo-website-template/assets/143704052/2e376a58-705b-4b6f-babf-856bb92605af)

**Comment by WillemIsendoorn** [comment]
Dat geldt ook voor de andere twee soorten bijlagen:
![image](https://github.com/ConductionNL/woo-website-template/assets/143704052/d0527002-d0a0-4275-8041-1f38a6f09306)

**Comment by remko48** [comment]
Op het moment klopt dit wel, ik zal aan @rubenvdlinde vragen wat er verder mee moet gebeuren

**Comment by remko48** [comment]
Opgelost en beschikbaar op https://conductionnl.github.io/woo-website-epe/
