### ISSUE TITLE
Weergave tabel nog niet correct

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#90]
Als de bezoek kiest voor de weergave in tabelvorm, dan ziet dat er zo uit:
![image](https://github.com/ConductionNL/woo-website-template/assets/143704052/f4f23d37-fea7-4b8c-a22d-6a74506bf313)

Wat mij betreft mag de eerste kolom vervallen. Dan na de kolom Categorie een kolom met de Samenvatting.
En de datums in de volgorde Ontvangst, Besluit en Publicatie. 
In de kolom Besluitdatum staat nu trouwens "Geen besluitdatum beschikbaar" maar dat is niet correct. Die is wel beschikbaar.
En dan de kolom Besluit: die mag weg.

**Comment by remko48** [comment]
- De eerste kolom is de Titel van het Woo-verzoek ik kan die verwijderen maar het lijkt mij onverstandig.
- Ik zal de volgorde veranderen.
- In de objecten die binnen komen zijn `Besluitsdatum` en `Besluit` niet gevuld hierdoor staat er dat er "Geen besluitdatum beschibkaar" is.
- In de kolom besluit staat wat voor besluit er genomen is e.g. "Niet openbaar gemaakt", "Deels openbaar gemaakt". Ik zou deze kolom ook weg kunnen halen

**Comment by WillemIsendoorn** [comment]
De Titel is toch hetzelfde als de Woo-categorie? 
De laatste kolom heeft niet veel toegevoegde waarde want alleen openbare besluiten zullen gepubliceerd worden.

**Comment by remko48** [comment]
Zoals vanochtend besproken zal ik de tabel veranderen naar: Onderwerp - Publicatiedatume - Samenvatting

**Comment by remko48** [comment]
Verwerkt en te zien op de [Woo website van Gemeente Epe](https://conductionnl.github.io/woo-website-epe/)
