### ISSUE TITLE
Het woord bijlage mag weg op 3 regels

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#91]
In dit scherm
![image](https://github.com/ConductionNL/woo-website-template/assets/143704052/79c6f0b0-4667-4d6b-b22e-28d8f5240e1c)

mag het woord Bijlage weg voor de eerste 3 regels.

**Comment by WillemIsendoorn** [comment]
En een meer logische volgorde is:
- Verzoek
- Besluit
- Inventarisatielijst

**Comment by remko48** [comment]
Gedaan en te zien op de [woo website van Epe](https://conductionnl.github.io/woo-website-epe/c303b326-6146-4b3d-96a2-96a8028f7f2b)
