### ISSUE TITLE
Huisstijl aanpassingen

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#93]
Dit lijstje heb ik al eerder doorgegeven maar is nog niet verwerkt. Daarom nogmaals via een issue:
•	Het logo van de gemeente Epe lijkt een stuk kleiner dan in het Figma-bestand en op [www.epe.nl](http://www.epe.nl/)
•	De lijntjes onder de titel van een WOO-verzoek zijn dunner dan op [www.epe.nl](http://www.epe.nl/). De titel lijkt overigens groter dan de gangbare titels op [www.epe.nl](http://www.epe.nl/)
•	Het klokje voor de datum van een WOO-verzoek lijkt me overbodig en kan de indruk wekken dat het WOO-verzoek maar een bepaalde periode online staat.
•	De achtergrondfoto moet vervangen worden door een seizoensonafhankelijke foto, anders vraagt het teveel beheer.
•	Er moeten pagina’s worden toegevoegd zoals https://www.epe.nl/over-deze-website en https://www.epe.nl/privacy en https://www.epe.nl/toegankelijkheid. Ook moet de site voldoen aan de WCAG / Besluit digitale toegankelijkheid en periodiek worden getoetst en een actuele toegankelijkheidsverklaring hebben.
•	Het gemeentelogo in de footer lijkt me overbodig
•	Een link naar [www.epe.nl](http://www.epe.nl/) zou goed zijn, zoals we bijvoorbeeld ook kruisverwijzen tussen [www.epe.nl](http://www.epe.nl/) en [www.epe.nl/epeverduurzaamt](http://www.epe.nl/epeverduurzaamt) 
•	Ik denk dat het zinvol is om toe te voegen hoe inwoners contact op kunnen nemen met de gemeente epe, zoals we bijvoorbeeld ook doen op [www.epe.nl](http://www.epe.nl/) via de footer en via https://www.epe.nl/contact-met-de-gemeente.
•	De footer is nu heel leeg en daardoor een groot blauw vlak.

**Comment by remko48** [comment]
- Ik zal het logo groter maken zodat het dezelfde grote heeft als het logo op [www.epe.nl](http://www.epe.nl/), is er een link naar het Figma-bestand zodat ik daar op kan meekijken om het thema beter te maken?
- Ik zal de lijnen onder de titels ook groter maken. De titel is inderdaad groter dan de titels op [www.epe.nl](http://www.epe.nl/) dit komt omdat we op de WOO in de cards gebruik maken van een `<h2>` element op [www.epe.nl](http://www.epe.nl/) wordt er in de cards een `<h3>` element gebruikt.
- Ik zal het klokje verwijderen.
- Welke afbeelding zou dat moeten zijn? Als je een voorkeur heeft voor een afbeelding en de link wilt delen kan ik dat meteen in de configuratie zetten.
- Ik zal dit aan [@rubenvdlinde](https://github.com/rubenvdlinde) vragen.
- Ik zal het logo in de footer optioneel maken
- Op het logo in de footer is er een verwijzing naar [www.epe.nl](http://www.epe.nl/)
- Ik zal met [@rubenvdlinde](https://github.com/rubenvdlinde) overleggen hoe we de footer dynamiser gaan maken om de footer beter te vullen.
- Dit komt omdat we de footer voor epe een minimale hoogte meegeven. Zodat we de afbeelding met het hert goed kunnen weergeven in de footer.

**Comment by PatrickYpkemeule** [comment]
de tegels op de pagina https://conductionnl.github.io/woo-website-noaberkracht/ zijn erg groot

**Comment by remko48** [comment]
De tegels op de [WOO-pagina van Noaberkracht](https://conductionnl.github.io/woo-website-noaberkracht/) zijn zo groot vanwege de `font-sizes` van Noaberkracht. 
Ik heb de `font-sizes` gebruikt uit de meegstuurde huistijl handboek, ik zal deze aanpassen zodat het beter past bij de website.

**Comment by remko48** [comment]
Eerste deel van dit issue gedaan:

- [X] - Ik zal het logo groter maken zodat het dezelfde grote heeft als het logo op [www.epe.nl](http://www.epe.nl/), is er een link naar het Figma-bestand zodat ik daar op kan meekijken om het thema beter te maken?
- [X] - Ik zal de lijnen onder de titels ook groter maken. De titel is inderdaad groter dan de titels op [www.epe.nl](http://www.epe.nl/) dit komt omdat we op de WOO in de cards gebruik maken van een `<h2>` element op [www.epe.nl](http://www.epe.nl/) wordt er in de cards een `<h3>` element gebruikt.
- [X] - Ik zal het klokje verwijderen.
- [ ] - Welke afbeelding zou dat moeten zijn? Als je een voorkeur heeft voor een afbeelding en de link wilt delen kan ik dat meteen in de configuratie zetten. 

 @WillemIsendoorn wanneer kan ik deze afbeelding ongeveer verwachten?
 > Ruben heeft het Figma-bestand van Epe. Ik heb een seizoensonafhankelijke foto opgevraagd.

- [ ] - Ik zal dit aan [@rubenvdlinde](https://github.com/rubenvdlinde) vragen.
  - Al een deel gedaan om aan de eisen van WCAG te voldoen
- [X] - Ik zal het logo in de footer optioneel maken
- [ ] - Op het logo in de footer is er een verwijzing naar [www.epe.nl](http://www.epe.nl/)
- [ ] - Ik zal met [@rubenvdlinde](https://github.com/rubenvdlinde) overleggen hoe we de footer dynamiser gaan maken om de footer beter te vullen.
- [ ] - Dit komt omdat we de footer voor epe een minimale hoogte meegeven. Zodat we de afbeelding met het hert goed kunnen weergeven in de footer.

**Comment by lencodes** [comment]
**Let op:** deze issues zijn alleen door Conduction intern in te zien.

We hebben drie issues aangemaakt, en gaan deze z.s.m. oppakken:

1. [Footer height minder hoog maken bij gebruik image;](https://conduction.atlassian.net/browse/XW-86)
2. [Volledige template WCAG-compliant maken](https://conduction.atlassian.net/browse/XW-87) en
3. [Footer content dynamisch inladen via .env](https://conduction.atlassian.net/browse/XW-88)

**Comment by WillemIsendoorn** [comment]
@remko48  Kan de grootte van de titel in de tegel nog aangepast worden? Dus een <h3? element?

**Comment by WillemIsendoorn** [comment]
@remko48 Bijgaand de foto die het hele jaar door gebruikt kan worden. Kijk maar of je hem passend krijgt.
![Koeien Epe](https://github.com/ConductionNL/woo-website-template/assets/143704052/49a87c42-a0f5-4142-84d1-0b5495d45e3f)

**Comment by remko48** [comment]
> @remko48 Kan de grootte van de titel in de tegel nog aangepast worden? Dus een <h3? element?

Dat zal helaas niet gaan. Als we het naar een `<h3>` element zetten staat het voor Epe goed maar voor alle andere gemeentes zoals Noordwijk en Noaberkracht niet meer.

Voor referentie:
Noordwijk h2
![image](https://github.com/ConductionNL/woo-website-template/assets/43807324/bcc260a2-b624-442c-994c-9d6d57ac5e2d)

Noordwijk h3
![image](https://github.com/ConductionNL/woo-website-template/assets/43807324/b46e87e1-b143-4522-8a17-cdbe3048bfd6)


Noaberkracht h2
![image](https://github.com/ConductionNL/woo-website-template/assets/43807324/bf533f98-5085-49be-a41c-5bbdc8852616)

Noaberkracht h3
![image](https://github.com/ConductionNL/woo-website-template/assets/43807324/ec958ce6-622b-4130-8d73-8b5575fbee12)

Tubbergen h2
![image](https://github.com/ConductionNL/woo-website-template/assets/43807324/f1bd9060-68e0-45ec-b3cf-328091b061e9)

Tubbergen h3
![image](https://github.com/ConductionNL/woo-website-template/assets/43807324/974cb275-377c-41b8-9b0f-5c4ea6ec1416)


We kunnen hier aankomende donderdag(12-10-2023) ook nog over spreken met iedereen er bij.

**Comment by remko48** [comment]
> @remko48 Bijgaand de foto die het hele jaar door gebruikt kan worden. Kijk maar of je hem passend krijgt. ![Koeien Epe](https://user-images.githubusercontent.com/143704052/273815462-49a87c42-a0f5-4142-84d1-0b5495d45e3f.jpg)

Bijgewerkt en staat nu op https://conductionnl.github.io/woo-website-epe/
Ook is de footer geupdate met content

**Comment by remko48** [comment]
De Woo-website van Epe voldoet volgens de online audit van [accessiBe](https://accessibe.com/) WCAG compliant.
https://accessibe.com/accessscan?website=https://conductionnl.github.io/woo-website-epe/

**Comment by remko48** [comment]
Ik heb de footer ook aangepast en die is nu een stuk lager dan eerst. 
Hij is nu ongeveer zo groot als de footer van epe zelf
https://conductionnl.github.io/woo-website-epe/

**Comment by remko48** [comment]
Met goedkeuring van @WillemIsendoorn kan dit issue gesloten worden

**Comment by WillemIsendoorn** [comment]
De test op https://accessibe.com/ geeft aan dat er nog diverse aspecten zijn waaraan niet voldaan wordt. Dat geldt o.a. voor het onderdeel Titles. Onze online adviseur vind dit nog onvoldoende.

Over de footer geeft hij aan:
Ten eerste is de footer niet digitaal toegankelijk. De linkjes geven bijvoorbeeld geen feedback als je erover heen gaat. Met de tegels werkt dit nu wel mooi. Mijn voorstel zou zijn om de linkjes op dezelfde manier op te maken en te laten reageren als op www.epe.nl
Ten tweede verwijzen de links naar Privacy en Over deze website naar www.epe.nl, terwijl dit in mijn beleving een andere website is. Tot verwijst de link naar Toegankelijkheid naar accesScan en dit is niet gangbaar (en ik denk niet toegestaan) voor overheidswebsites.

**Comment by WillemIsendoorn** [comment]
Voor de verwijzing naar Toegankelijkheid zou een eigen pagina gemaakt moeten worden omdat deze webpagina's een eigen toegankelijkheidsverklaring behoeven. Zie bijvoorbeeld: https://www.epe.nl/toegankelijkheid 
Daar kan niet zomaar naar verwezen worden.

Voor het onderdeel "Over deze website" zou een pagina gemaakt moeten worden door Conduction/XXLNC zoals afgelopen donderdag besproken. Dit kan een algemene tekst zijn die voor elke gemeente gelijk is.

Voor Privacy kan nu verwezen worden naar https://www.epe.nl/privacy. Daar moeten we een aparte pagina voor maken in samenwerking met onder Functionaris Gegevensbescherming en/of onze Privacy Officer.

**Comment by remko48** [comment]
Ik ga dit issue sluiten en twee andere issues aanmaken voor de twee bovenstaande comments.
De twee comments vallen onder een issue voor WCAG en niet meer onder dit issue.
