### ISSUE TITLE
Testcase 2 negatief

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#94]
Ik heb bij zaak 131340 de publicatiedatum op 3-10 gezet. Deze blijft echter zichtbaar.

**Comment by bbrands02** [comment]
Ik denk dat deze na 10 minuten verwijderd is inderdaad? Ik zie geen zaak meer met nummer 131340. Voor de zekerheid kan dit opnieuw getest worden, maar er is dus 10 min minimaal nodig voordat de synchronisatie weer afgaat.

**Comment by WillemIsendoorn** [comment]
Gisteren heb ik dit diverse keren getest, zeker na 10 minuten. Toen werkte het niet. Nu wel!
