### ISSUE TITLE
Documenten kunnen niet geopend worden

### ISSUE THREAD

**Issue by WillemIsendoorn** [ConductionNL/woo-website-template#96]
Als ik een document wil openen dat bij een Woo-verzoek hoort, dan krijgen we de volgende foutmelding:
![image](https://github.com/ConductionNL/woo-website-template/assets/143704052/c38fa0ab-c9e0-4819-b001-c4fdedf05deb)

**Comment by WillemIsendoorn** [comment]
Net opnieuw getest. Bij een aantal documenten werkte het.
En daarna kreeg ik (ook bij een document wat eerder wel opende) de melding:
{"message" => "File not found or file doesn't belong to the configured schema."}

**Comment by bbrands02** [comment]
Zou opgelost moeten zijn
